### ISSUE TITLE
Incomplete README.md

### ISSUE THREAD

**Issue by tetomonti** [montilab/yQTLpipeline#1]
In the README file, there is 

**2. Run the yQTL Pipeline**
...

However, you do not specify where the yQTL pipeline (and how to download it). I presume, something like

**1.4 "Install" yQTL pipeline**

```
cd /path/to/folder/
git clone https://github.com/montilab/yQTLpipeline.git
```

will be needed. 

Also, in "2. Run the yQTL Pipeline", when running on local your instructions says:

```
$ module load R/4.1.2 
$ ./nextflow -c Config.config run Prepare.nf 
$ ./nextflow -c Config.config run Analysis.nf 
$ ./nextflow -c Config.config run Report.nf 
```

which presumes that both the nextflow command and the *.nf files are in the same folder? This is likely not correct.

**Comment by Vanessa104** [comment]
Resolved now. Documentation is updated.
